Removed implicit autoload registration
koriym/dii pull request #25
Opened 2021-01-15 12:17 UTC by koriym

# 概要

* 暗黙的なオートロード登録の廃止
* オートロードでファイルが見つからない場合のエラーの抑制

# 詳細

* Yiiのオートローダーはclass_exists($class)でクラスファイルがない場合にエラーを発生させてしまいます。

* このPRはYiiBaseに代わりサイレントオートローダーに変わったautoloadメソッドを保持したMyYiiBaseを使用し、クラスファイルがなくてもエラーを発生させません。アノテーションリーダーが存在しないクラスを読み込む場合のエラーを抑制します。

* Yiiのオートローダー機構を使いながらcomposer のautoloadとして機能します。YiiBaseが行っていたような暗黙的なオートローダー登録が廃止されます。

2021-01-15 14:12 UTC, NaokiTsuchiya requested changes

2021-01-15 14:12 UTC, NaokiTsuchiya commented on demo/public/index.php
> +laod: {
```suggestion
load: {
```

2021-01-15 14:21 UTC, NaokiTsuchiya commented on src/MyYiiBase.php
> +                    foreach ($includePaths as $path) {
wrong indent?

2021-01-15 14:23 UTC, koriym commented on demo/public/index.php
> +laod: {
label deleted ^^;

2021-01-15 14:52 UTC, koriym commented on src/MyYiiBase.php
> +                    foreach ($includePaths as $path) {
Try in local. Looks different??

2021-01-15 15:03 UTC, NaokiTsuchiya commented on src/MyYiiBase.php
> +                    foreach ($includePaths as $path) {
Looks good in Local.  Why? 🤔

2021-01-15 15:54 UTC, koriym commented on src/MyYiiBase.php
> +                    foreach ($includePaths as $path) {
Tab!?

2021-01-16 05:31 UTC, NaokiTsuchiya commented on src/MyYiiBase.php
> +                    foreach ($includePaths as $path) {
Existing code was using tab indent 😅

2021-01-16 07:00 UTC, NaokiTsuchiya commented on demo/public/index.php
> -Yii::createWebApplication($config)->run();
ここのYiiの実態は `yiidii.php` のようでした。

なので `yiidii.php` をautoloadに追加したら動くのかなと試してみたのですが、別の場所でエラーになってしまいました 🤔 

これは特に問題ないですかね？

2021-01-17 02:42 UTC, koriym commented on demo/public/index.php
> -Yii::createWebApplication($config)->run();
もう少し詳しく教えてもらっていいでしょうか？

2021-01-17 04:21 UTC, NaokiTsuchiya commented on demo/public/index.php
> -Yii::createWebApplication($config)->run();
これまでのDemoは `yiidii.php` をautoloadしていたので、`Yii::createWebApplication($config)->run()` は `yiidii.php`に定義された `class Yii extends Dii` が呼び出され、`Yii -> Dii -> YiiBase` という呼び出しの関係でした。

今回の変更で `yiidii.php` のautoloadがなくなり、 `Yii::someStaticMethod()` のように実行すると `vendor/yiisoft/yii/yii.php` 内の `class Yii extends YiiBase` 呼び出されるようになっています。
 `Yii` の呼び出しで `Dii` 側の処理が入らなくなることによって、autoload以外の点で何か影響が無いのか？という点が気になりました。

2021-01-17 04:27 UTC, NaokiTsuchiya commented on demo/public/index.php
> -Yii::createWebApplication($config)->run();
以下のように変更したところ、 `Yii::createWebApplication($config)->run();` でもDemoが動作することを確認できました
https://github.com/koriym/dii/compare/autoload...NaokiTsuchiya:autoload

2021-01-17 04:37 UTC, NaokiTsuchiya commented on demo/public/index.php
> -Yii::createWebApplication($config)->run();
上記で `MyYiiBase` が `Yii::something()` を実行しても `class Yii extends Dii` が呼び出されるようになったので、`YiiBase`は完全に呼び出されなくなったかもしれないです。

2021-01-22 02:18 UTC, amashigeseiji commented on autoload.php
> +spl_autoload_register([MyYiiBase::class, 'autoload']);
https://github.com/yiisoft/yii/blob/master/framework/YiiBase.php#L910-L911

こちらの最終行に `YII_PATH.'/base/interfaces.php'` の読み込みが行われています。
現状のままだと、インターフェースが読まれないかもしれません。

2021-01-22 04:57 UTC, sun3bow commented on src/MyYiiBase.php
> +				else
else句を`{}`で囲わないとforeach以降がelse句の外に出てしまうかと思われますがどうでしょうか？

2021-01-22 07:44 UTC, koriym commented
#26 に関連してこのPRを閉じます。

2021-01-22 07:44 UTC, closed without merging

2021-01-22 07:49 UTC, koriym commented on src/MyYiiBase.php
> +				else
指摘の通りです！